import { SHOPIFY_CHANNEL_TERMS_VERSION } from "./constants";

export const CHANNEL_TERMS_TITLE = "Shopify Channel Terms of Service";
export const CHANNEL_TERMS_UPDATED = "September 28, 2026";

export const CHANNEL_TERMS_TEXT = `These Shopify Channel Terms of Service (the "Channel Terms") constitute a legally binding contract between you ("Wholesaler," "you," or "your") and The Perfect Part, LLC ("Company," "we," "us," or "our"), with its place of business at Pompano Beach, Florida 33069. These Channel Terms are an addendum to the Wholesale Program Terms of Service (the "Program Terms"). If these Channel Terms conflict with the Program Terms, these Channel Terms control. These Channel Terms are governed by the laws of the State of Florida, without regard to conflict-of-laws rules. They do not apply the law of Arizona or California. The Company's place of business for these Channel Terms is Broward County, Florida.

PLEASE READ THESE CHANNEL TERMS CAREFULLY. THEY REQUIRE BINDING ARBITRATION ON AN INDIVIDUAL BASIS, WAIVE CLASS ACTIONS AND JURY TRIALS, AND REQUIRE YOU TO PAY ALL ARBITRATION COSTS AND THE COMPANY'S ATTORNEYS' FEES.

1. ACCEPTANCE. By clicking "I agree," connecting a Shopify store, saving a payment card, listing a product, or allowing us to charge your card, you agree to these Channel Terms for yourself and for the business on your wholesale account. You represent that you have authority to bind that business. If you do not agree, do not connect a store and do not list products. Clicking "I agree" is your electronic signature under the federal E-SIGN Act and the Florida Uniform Electronic Transaction Act, Florida Statutes section 668.50. We store your account, the user who accepted, the date and time, and version ${SHOPIFY_CHANNEL_TERMS_VERSION}. We may revise these Channel Terms. The revised version is binding when you click "I agree" on it. You may not list additional products until you accept the revised version. An order already charged remains under the version in effect at the time of that charge.

2. THE CHANNEL. You may connect up to five (5) Shopify stores, each denominated in United States dollars. You may list our products on those stores. Your customer pays you, on your store, at prices you set. We charge the payment card you save for our wholesale price in effect on the day the paid order reaches us, at your tier that day, including any welcome discount then in effect. That charge is not the price your customer paid you. Shipping to an address in the United States, including PO Boxes, Alaska, and Hawaii, is $0. A ship-to country other than the United States adds a flat charge of $18.99 per order. We do not collect sales tax or customs duty from you on channel orders. Your customer outside the United States may be required to pay duty, tax, or a carrier fee upon delivery, and those amounts are solely your customer's and yours. When we accept an order, we ship to the address received, the same business day or the next business day, if the goods and a complete address are available. We transmit the carrier and tracking number to your Shopify order. Your Shopify store, not the Company, notifies your customer. We do not email your customer. Card statements identify the charge as THE PERFECT PART.

3. YOUR STORE AND YOUR CUSTOMER. You are the merchant of record to your customer. You alone set titles, descriptions, prices, policies, advertising, and customer service. You are solely responsible for your Shopify store, your listings, your Shopify fees, your taxes, your refunds to your customer, and any chargeback or payment dispute with your customer. Such a dispute is exclusively between you and your customer. You shall not name the Company as a party, except to request a refund from us under these Channel Terms. You shall indemnify us for any such dispute as set forth below.

4. AUTHORIZATION TO CHARGE. You authorize the Company to charge the saved card for each accepted channel order, including a single automatic retry if a charge is declined, and to charge again after you save a new card for orders then waiting on payment. If we charge you and are then unable to create our fulfillment order, we will refund that charge. If the card is missing or declined, we have no duty to ship.

5. SHIPPING ADDRESS. If an order lacks a street or a country, we will not charge and we will not ship. If you correct that Shopify order before we have charged it, we may then charge and ship to the corrected address. After we charge you and create our fulfillment order, the ship-to address is fixed as received. A later edit, cancellation, or refund inside Shopify does not modify our shipment and does not obligate us to refund. A request to cancel or to change an address shall be submitted only through Support in the wholesale portal, with the order number. We may grant that request only if the goods have not shipped, and we have no obligation to do so. THE COMPANY IS NOT RESPONSIBLE FOR ANY ADDRESS YOUR CUSTOMER ENTERED, INCLUDING A WRONG STREET, A MISSING UNIT NUMBER, OR AN UNINTENDED PO BOX.

6. STOCK, PAUSE, AND NON-DELIVERABLE DESTINATIONS. Inventory displayed on your store is updated about every fifteen (15) minutes and is checked again before we charge. If we lack sufficient goods when the order arrives, we will not charge and we will not ship, and you shall refund your customer. If you pause new orders, sales during that pause are not charged and are not shipped, and you shall refund your customer. If we pause or close your wholesale account, we may remove our listings from your connected Shopify stores. We do not warrant delivery to every country. If a carrier cannot deliver, we may already have charged you. We will notify you. Any refund is solely at our discretion through Support.

7. RISK OF LOSS AND RETURNS. Title and risk of loss pass to you, for shipment to your customer, when the carrier receives the goods. We do not alter the return address on the package. WE ARE NOT LIABLE FOR LOSS, DELAY, THEFT, OR DAMAGE AFTER THE CARRIER RECEIVES THE GOODS. A refund after shipment, a return to our facility, a damaged item, or an incorrect item is not automatic. You must contact Support with the order number and photographs. We may refund, replace, or deny the request in our sole discretion. We are not responsible for your customer's dissatisfaction, your lost profits, or reviews on your store.

8. LISTINGS. We may copy product title, description, and photographs to your store. We remove our business name, website, and telephone number from the written text. Photographs may still contain our name. You may edit a listing after it is published. We have no obligation to push later changes to our title, description, or photographs onto a listing you already published. Price changes you make on Shopify are yours. If we discontinue a product, we may set the listing quantity to zero. If you remove a listing, we may delete that product from the Shopify store you selected.

9. DISCLAIMER AND LIMITATION OF LIABILITY. THE CHANNEL, PRODUCTS, LISTINGS, INVENTORY FIGURES, SHIPPING ESTIMATES, AND PORTAL ARE PROVIDED "AS IS" AND "AS AVAILABLE," WITH ALL FAULTS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY DISCLAIMS EVERY WARRANTY, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. THE COMPANY IS NOT RESPONSIBLE OR LIABLE FOR YOUR SHOPIFY STORE, YOUR CUSTOMERS, YOUR PRICES, YOUR CHARGEBACKS, YOUR TAXES, YOUR SHOPIFY FEES, CUSTOMS DUTY, ANY ADDRESS, ANY CARRIER, ANY SHOPIFY FAILURE, ANY DELAY, ANY INVENTORY FIGURE, ANY PAUSED OR DECLINED ORDER, OR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, REVENUE, GOODWILL, OR BUSINESS, WHETHER IN CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY'S TOTAL LIABILITY ARISING OUT OF A CHANNEL ORDER SHALL NOT EXCEED THE AMOUNT YOU ACTUALLY PAID THE COMPANY FOR THAT ORDER. IF A LAW DOES NOT ALLOW A LIMIT, THE COMPANY'S LIABILITY IS LIMITED TO THE MINIMUM THE LAW PERMITS.

10. INDEMNIFICATION. You shall defend, indemnify, and hold harmless the Company and its members, managers, employees, and agents from and against any claim, demand, loss, damage, liability, cost, and expense, including reasonable attorneys' fees, arising out of or related to your Shopify store, your customers, your listings, your prices, your advertising, any chargeback, any product you resold, any address your customer supplied, your breach of these Channel Terms, or your violation of law or of any third-party right.

11. BINDING ARBITRATION, CLASS WAIVER, AND FEES. PLEASE READ THIS SECTION. IT REQUIRES ARBITRATION AND LIMITS WHERE AND HOW DISPUTES ARE HEARD.

11.1 Exclusive remedy. Any dispute, claim, or controversy arising out of or relating to these Channel Terms, the channel, any charge, any shipment, or the relationship between you and the Company (a "Dispute") shall be resolved only by final and binding individual arbitration. You and the Company waive any right to a court trial or a jury trial, except that either party may seek a court order solely to compel arbitration or to confirm or enforce an arbitration award. The Federal Arbitration Act governs this Section 11.

11.2 Rules and place. Arbitration shall be administered by the American Arbitration Association under its Commercial Arbitration Rules then in effect. The seat and venue shall be Broward County, Florida. The Company maintains its place of business at Pompano Beach, Florida 33069. The arbitrator shall apply the substantive law of the State of Florida, without regard to conflict-of-laws rules. Proceedings may be conducted by video if the arbitrator so orders. The arbitrator has no authority to award relief prohibited by Section 9.

11.3 Individual only. Disputes shall be brought only in an individual capacity. Class, collective, consolidated, and representative proceedings are waived. The arbitrator may not consolidate claims of more than one wholesaler and may not preside over any class or representative proceeding.

11.4 Costs paid by you. You shall pay, in full, all arbitration filing fees, case-management fees, arbitrator fees, hearing fees, and other tribunal costs, for both you and the Company. You shall also pay the Company's reasonable attorneys' fees and costs incurred in the arbitration, in full, regardless of which party prevails. This Section 11.4 replaces any Program Terms provision that would split arbitration costs or award fees only to a prevailing party, for Disputes under these Channel Terms.

11.5 Survival. This Section 11 survives termination of your account and of these Channel Terms.

12. GENERAL. These Channel Terms, together with the Program Terms, are the entire agreement regarding the channel. If any provision other than Section 11 is held unenforceable, the remainder stays in effect. If any part of Section 11 is held unenforceable, the remainder of Section 11 stays in effect. You may not assign these Channel Terms. We may assign them. Our failure to enforce a provision is not a waiver. Notices to you may be sent to the email on your wholesale account. Section headings are for convenience only.`;
